# Generated by Django 4.0.5 on 2022-06-14 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0003_newsletterrecipients_review_profile_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_url',
            new_name='url',
        ),
    ]
